c.content.images = True
c.content.javascript.enabled = True
c.content.plugins = True
c.content.private_browsing = False
c.content.proxy = "system"
c.content.ssl_strict = True
c.content.xss_auditing = True
c.input.insert_mode.plugins = True
c.window.title_format = "{private}{perc}{title}{title_sep}qutebrowser (in nspawn container)"
