#!/bin/bash

function help() {
	echo "usage: $0 CONTAINER_NAME CONTAINER_NAME ..."
	exit 1
}

if [ $# -eq 0 ]; then
	help
else
	NSPAWN_FILES_DIR=$(cd "$(dirname "$0")" || exit 1; pwd)
	CONTAINERS=( "$@" )
fi

for CONTAINER in "${CONTAINERS[@]}"; do
	echo "Build and install $CONTAINER"
	cd "$NSPAWN_FILES_DIR/$CONTAINER" || exit 1
	make
	make uninstall
	make install
	make clean
done
