#!/bin/bash

# shellcheck disable=SC2154
if [ "$container" != "mkosi" ]; then
    if [[ $(mkosi --version | awk '{print $$2}' | cut -d . -f 1) -ge 15 ]]; then
        exec mkosi-chroot "$SCRIPT" "$@"
    fi
fi

# Prepare for using normal user 'builder'
NORMAL_USER="builder"
useradd -m ${NORMAL_USER}
gpasswd -a ${NORMAL_USER} wheel
echo "${NORMAL_USER}:${NORMAL_USER}" | chpasswd
sed -e 's/# %wheel ALL=(ALL) ALL/%wheel ALL=(ALL) ALL/' /etc/sudoers -i
