#!/bin/bash

# Install required config
mv -f /locale.gen /etc/locale.gen
mv -f /locale.conf /etc/locale.conf
mv -f /pacman.conf /etc/pacman.conf
mv -f /nsswitch.conf /etc/nsswitch.conf
mkdir -p /etc/pacman.d/hooks
mv -f /mirrorupgrade.hook /etc/pacman.d/hooks/mirrorupgrade.hook
mv -f /mirrorlist /etc/pacman.d/mirrorlist

# Remove /etc/securetty to enable root login
rm -f /etc/securetty

# Prepare locale
locale-gen
